### PR TITLE
feat: use new JSON format, add install script

### LINKED ISSUE #2: Make pull request with official files repo to add this themes to default ones
You need to open PR with themes included in files repo to include them as default files.

files repo - https://github.com/files-community/Files

### LINKED ISSUE #6: solid base background
Kind of disappointed that the main window isn't coloured (example image below, the icon uses a mocha background colour)
image

Is this a limitation at all or just an oversight? Or did we install wrong because that's possible too

### LINKED ISSUE #7: Custom theme support removed in Files 2.4.21
The option to add custom themes through files was removed as noted in several GitHub issues:

https://github.com/files-community/Files/issues/10315
https://github.com/files-community/Files/issues/10542
https://github.com/files-community/Files/issues/10885

The [updated documentation](https://files.community/docs/configuring/custom-themes) suggests some ways to customize it to an extent. Is there any way to integrate catppuccin to this new version?

### PR DESCRIPTION
**Pull request by nekowinston**
docs need to be updated, script should work already

### CODE REVIEW

**Review by sgoudham — CHANGES_REQUESTED** [review]
Posting in here for transparency:

I noticed that when I tried to run the script, the `-AsHashtable` wasn't recognised as a flag. I found that this flag was introduced in Powershell 6.0, whereas I had Powershell 5.1 running on my Windows 10 machine.

Then, I tried to convert the JSON into a Hashtable manually using the following code:

```psh
$palette = @{}
$json = Invoke-WebRequest -Uri "https://github.com/catppuccin/palette/raw/v1.1.0/palette.json" | ConvertFrom-Json
(ConvertFrom-Json $json).psobject.properties | Foreach { $palette[$_.Name] = $_.Value }
```

Unfortunately, this errors on https://github.com/catppuccin/windows-files/pull/8/files#diff-50d51a233d8ff4886061fc5cf1a03642de1f64b3625903e4f876e8cd2a3f5806R14 because it's unable to index into the `$palette` variable.

That's all I had time for, maybe I'm doing something obvious that's wrong but figured I'd post in here anyways. 

I think we'd want to rework the script so that it's runnable on Powershell 5.1? If not, we can just merge and say that at least Powershell 6.0 is required.

**Comment by nekowinston** [comment]
Closing all other issues since the complete theming mechanics have changed

**Comment by yair100** [comment]
@nekowinston thank you for updating this! If you're interested, feel free to open a PR on the Files website linking to this repo https://github.com/files-community/Website/.

**Comment by sgoudham** [comment]
Just leaving this here for the future, I wanted to try the following code to see if it would work on Powershell 5.1

https://stackoverflow.com/questions/75182380/how-to-convert-nested-json-into-hashtable-in-powershell
```
function Convert-PSCToHashTable
{
  param(
    $InputObject, 
    [int]$Depth = 5
  )

  if($Depth -gt 0){
    if($InputObject -is [System.Collections.IList]){
      return @($InputObject |ForEach-Object {Convert-PSCToHashTable $_ -Depth ($Depth - 1)})
    }

    if($InputObject.psobject.BaseObject -is [System.Management.Automation.PSCustomObject]){
      $ht = @{}
      foreach($prop in $InputObject.psobject.Properties){
        $ht[$prop.Name] = Convert-PSCToHashTable $prop.Value -Depth ($Depth - 1)
      }
      return $ht
    }
  }

  return $InputObject
}

$object = ConvertFrom-Json $json
$hashtable = Convert-PSCToHashTable $object
```

I'll probably try it out later when I'm on windows just out of curiosity

**Pull request merged**
